In [1]:
import numpy as np
import torch

In [2]:
mat = np.random.rand(3,2)
print(mat)
np.argsort(mat, axis=1)

[[0.19049734 0.40059194]
 [0.8119759  0.42094139]
 [0.93476493 0.33293472]]


array([[0, 1],
       [1, 0],
       [1, 0]])

In [4]:
mat1 =  torch.from_numpy(mat)
mat2 = torch.from_numpy(mat)
f = []
f.append(mat1)
f.append(mat2)
print(f)
f =  torch.cat(f, 0)
print(f)

[tensor([[0.1905, 0.4006],
        [0.8120, 0.4209],
        [0.9348, 0.3329]], dtype=torch.float64), tensor([[0.1905, 0.4006],
        [0.8120, 0.4209],
        [0.9348, 0.3329]], dtype=torch.float64)]
tensor([[0.1905, 0.4006],
        [0.8120, 0.4209],
        [0.9348, 0.3329],
        [0.1905, 0.4006],
        [0.8120, 0.4209],
        [0.9348, 0.3329]], dtype=torch.float64)


In [7]:
pid1 = torch.Tensor([1])
pid2 = torch.Tensor([2])
pids =[]
pids.extend(pid1)
pids.extend(pid2)
print(pids)
pids =np.asarray(pids)
print(pids)

[tensor(1.), tensor(2.)]
[1. 2.]


In [22]:
mat =[[1,1,1,1],[2,2,2,2],[3,3,3,3]]
mat = np.array(mat)
mat1 = torch.from_numpy(mat)
mat2 = torch.from_numpy(mat)
m, n = mat1.size(0), mat2.size(0)
distmat = torch.pow(mat1,2).sum(dim=1, keepdim=True).expand(m,n) + \
          torch.pow(mat2, 2).sum(dim=1, keepdim=True).expand(n, m).t()
print(torch.pow(mat1,2).sum(dim=1, keepdim=True).expand(m,n))
print(torch.pow(mat2, 2).sum(dim=1, keepdim=True).expand(n, m).t())
print(distmat)
distmat.addmm_(1, -2, mat1, mat2.t())
distmat = distmat.numpy()
print(distmat)

tensor([[ 4,  4,  4],
        [16, 16, 16],
        [36, 36, 36]])
tensor([[ 4, 16, 36],
        [ 4, 16, 36],
        [ 4, 16, 36]])
tensor([[ 8, 20, 40],
        [20, 32, 52],
        [40, 52, 72]])
[[ 0  4 16]
 [ 4  0  4]
 [16  4  0]]


In [24]:
num_list_1 = [x for x in range(10)]
num_list_2 = [x for x in range(10)]
num_list =  []
num_list.append(num_list_1)
num_list.append(num_list_2)
print(num_list)
num_list = np.array(num_list)
num_list = num_list.sum(0)
print(num_list)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
[ 0  2  4  6  8 10 12 14 16 18]


In [26]:
binary = np.asarray([True,False,True,False,False])
bin_inv = np.invert(binary)
print(bin_inv)

[False  True False  True  True]
